name: TagBot
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed] 
  workflow_dispatch:
permissions:
  contents: write 
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
